# Generated by Django 4.2.4 on 2023-08-17 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
        migrations.AddField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('Хочу научиться', 'Хочу научиться'), ('Могу научить', 'Могу научить')], default='Хочу научиться', max_length=100),
        ),
        migrations.AddField(
            model_name='ads',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
